routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::view('/', 'frontend.pages.index')->name('/');
Route::view('about-us', 'frontend.pages.about')->name('about');
Route::view('contact-us', 'frontend.pages.contact')->name('contact');
Route::get('F&Q', 'getPagesCtrl@faq')->name('faq');
Route::get('site_activities', 'getPagesCtrl@site_activities')->name('site_activities');
Route::get('site_activities/{id:slug}', 'getPagesCtrl@site_activities_details')->name('site_activities_details');
Route::post('programs/{id:slug}/set_story', 'SuccessStoryController@store')->name('stories.store');
Route::post('programs/{id:slug}/set_help', 'NeedHelpController@store')->name('helps.store');
Route::view('eventDetails', 'frontend.pages.eventDetails')->name('eventDetails');
Route::view('videos', 'frontend.pages.videos')->name('videos');
Route::get('program/{id:slug}', 'getPagesCtrl@program')->name('program');
Route::view('new-news', 'backend.pages.news.new')->name('newNews');



Route::get('/home', 'HomeController@index')->name('home');
Route::get('our_news/{id:slug}','newsCtrl@show')->name('News_Show');
Route::get('site_news/{id:slug}','newsCtrl@showForUser')->name('Site_News_Show');
Route::get('site_news','newsCtrl@SiteIndex')->name('Site_News_Page');

Route::resource('news', 'newsCtrl')->except([
    'show',
]);
Route::resource('activities', 'ActivityController');
Route::resource('faqs', 'FaqController');
Route::resource('programs', 'ProgramController');
Route::resource('stories', 'SuccessStoryController')->except(['store','show','edit','index']);
Route::resource('helps', 'NeedHelpController')->except(['store','show','edit','index']);
Route::resource('slides', 'SliderController')->except(['show','edit']);
Route::resource('talks', 'TalkController')->except(['show','edit']);
Route::resource('mails', 'ContactUsController')->except(['show','edit']);
Route::resource('edumesgs', 'EduMesgController');
Route::resource('settings', 'SettingController');



Route::group(['middleware' => ['auth']], function()
{

    Route::get('settings', 'SettingController@index')->name('settings');
    Route::view('admin', 'backend.pages.index')->name('admin');

});

    Auth::routes(['register' => false,'reset'=>false]);

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Setting extends Model
{
    protected $fillable = [
        'key',
        'value',
    ];

    use SoftDeletes;

}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $counter1_name = null;      $counter2_name = null;      $counter3_name = null;     $counter4_name = null;
        $counter1_value = null;     $counter2_value = null;     $counter3_value = null;    $counter4_value = null;
        $orange_number = null;      $vodafoon_number = null ;   $bank_account = null;      $account_code = null;
        $fb_link = null;            $insta_link = null;         $youtube_link = null ;      $phone1 = null;
        $phone2 = null ;            $email = null;

        if(\DB::table('settings')->where('key','counter1_name')->count()){
            $counter1_name = \DB::table('settings')->where('key','counter1_name')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter1_value')->count()){
            $counter1_value = \DB::table('settings')->where('key','counter1_value')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter2_name')->count()){
            $counter2_name = \DB::table('settings')->where('key','counter2_name')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter2_value')->count()){
            $counter2_value = \DB::table('settings')->where('key','counter2_value')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter3_name')->count()){
            $counter3_name = \DB::table('settings')->where('key','counter3_name')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter3_value')->count()){
            $counter3_value = \DB::table('settings')->where('key','counter3_value')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter4_name')->count()){
            $counter4_name = \DB::table('settings')->where('key','counter4_name')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','counter4_value')->count()){
            $counter4_value = \DB::table('settings')->where('key','counter4_value')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','orange_number')->count()){
            $orange_number = \DB::table('settings')->where('key','orange_number')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','vodafoon_number')->count()){
            $vodafoon_number = \DB::table('settings')->where('key','vodafoon_number')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','bank_account')->count()){
            $bank_account = \DB::table('settings')->where('key','bank_account')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','account_code')->count()){
            $account_code = \DB::table('settings')->where('key','account_code')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','fb_link')->count()){
            $fb_link = \DB::table('settings')->where('key','fb_link')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','insta_link')->count()){
            $insta_link = \DB::table('settings')->where('key','insta_link')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','youtube_link')->count()){
            $youtube_link = \DB::table('settings')->where('key','youtube_link')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','phone1')->count()){
            $phone1 = \DB::table('settings')->where('key','phone1')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','phone2')->count()){
            $phone2 = \DB::table('settings')->where('key','phone2')->select('value')->first()->value;
        }
        if(\DB::table('settings')->where('key','email')->count()){
            $email = \DB::table('settings')->where('key','email')->select('value')->first()->value;
        }

        return view('backend.pages.settings.index',
            compact('counter1_name','counter1_value','counter2_name',
                            'counter2_value','counter3_name','counter3_value',
                            'counter4_name','counter4_value', 'orange_number',
                            'vodafoon_number','bank_account','account_code',
                            'fb_link','insta_link','youtube_link','phone1',
                            'phone2','email'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $data = $request->validate([
            'counter1_name'=>'required|string',
            'counter1_value'=>'required|integer',
            'counter2_name'=>'required|string',
            'counter2_value'=>'required|integer',
            'counter3_name'=>'required|string',
            'counter3_value'=>'required|integer',
            'counter4_name'=>'required|string',
            'counter4_value'=>'required|integer',
            'orange_number'=>'required|string',
            'vodafoon_number'=>'required|string',
            'bank_account'=>'required|string',
            'account_code'=>'required|string',
            'fb_link'=>'required|url',
            'insta_link'=>'required|url',
            'youtube_link'=>'required|url',
            'phone1'=>'required|string',
            'phone2'=>'required|string',
            'email'=>'required|email',
        ]);
        $list = [
            0 =>[
                'key'=>'counter1_name',
                'value'=>$data['counter1_name']
            ],
            1=>[
                'key'=>'counter1_value',
                'value'=>$data['counter1_value']
            ],
            2 =>[
                'key'=>'counter2_name',
                'value'=>$data['counter2_name']
            ],
            3=>[
                'key'=>'counter2_value',
                'value'=>$data['counter2_value']
            ],
            4 =>[
                'key'=>'counter3_name',
                'value'=>$data['counter3_name']
            ],
            5=>[
                'key'=>'counter3_value',
                'value'=>$data['counter3_value']
            ],
            6=>[
                'key'=>'counter4_name',
                'value'=>$data['counter4_name']
            ],

            7=>[
                'key'=>'vodafoon_number',
                'value'=>$data['vodafoon_number']
            ],
            8=>[
                'key'=>'bank_account',
                'value'=>$data['bank_account']
            ],

            9=>[
                'key'=>'insta_link',
                'value'=>$data['insta_link']
            ],
            10=>[
                'key'=>'youtube_link',
                'value'=>$data['youtube_link']
            ],
            11=>[
                'key'=>'phone1',
                'value'=>$data['phone1']
            ],
            12=>[
                'key'=>'phone2',
                'value'=>$data['phone2']
            ],
            13=>[
                'key'=>'email',
                'value'=>$data['email']
            ],
            14=>[
                'key'=>'account_code',
                'value'=>$data['account_code']
            ],
            15=>[
                'key'=>'fb_link',
                'value'=>$data['fb_link']
            ],
            16=>[
                'key'=>'orange_number',
                'value'=>$data['orange_number']
            ],
            17=>[
                'key'=>'counter4_value',
                'value'=>$data['counter4_value']
            ],

        ];



       foreach ($list as $key => $item){
           if(Setting::where('key',$item['key'])->count()){
               $setting= Setting::where('key',$item['key'])->first();
               $setting->value = $item['value'];
               $setting->save();
           }else{
               $setting = new Setting();
               $setting->key = $item['key'];
               $setting->value = $item['value'];
               $setting->save();
           }

       }
        session()->flash('success','تم حفظ الخبر الجديد بنجاح، شكراً لك!');
        return  back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Setting $setting)
    {
        //
    }
}

resources/views/backend/pages/settings/index.blade.php
@extends('backend.app')
@section('title') Settings @stop
@section('content')
    <!-- Breadcomb area Start-->
    <div class="breadcomb-area" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcomb-list">
                        <div class="row" dir="rtl">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="notika-icon notika-support"></i>
                                    </div>
                                    <div class="breadcomb-ctn" style="margin-right: 20px;">
                                        <h2>الإعدادات العامة</h2>
                                        <p></p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcomb area End-->
    <!-- Invoice area Start-->
    <div class="invoice-area ">
        <div class="container">

            <div class="row" style="text-align: right; direction: rtl" >

                    <div class="col-lg-12 col-md-12 " >
                        <form action="{{route('settings.store')}}" method="post">
                            @csrf
                        <div class="invoice-wrap">
                                <div class="form-group">
                                    <h4 style="color: #0B792F; margin-bottom: 40px;">العدادات</h4>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>اسم العداد</span>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" class="form-control" name="counter1_name" value="{{$counter1_name??''}}" required>
                                        </div>
                                        <div class="col-md-1">
                                            <span>العدد</span>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="number" min="1" class="form-control" name="counter1_value"  value="{{$counter1_value??''}}" required>
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>اسم العداد</span>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" class="form-control" name="counter2_name" value="{{$counter2_name??''}}" required>
                                        </div>
                                        <div class="col-md-1">
                                            <span>العدد</span>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="number" min="1" class="form-control" name="counter2_value" value="{{$counter2_value??''}}" required>
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>اسم العداد</span>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" class="form-control" name="counter3_name" value="{{$counter3_name??''}}" required>
                                        </div>
                                        <div class="col-md-1">
                                            <span>العدد</span>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="number" min="1" class="form-control" name="counter3_value" value="{{$counter3_value??''}}" required>
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>اسم العداد</span>
                                        </div>
                                        <div class="col-md-6">
                                            <input type="text" class="form-control" name="counter4_name" value="{{$counter4_name??''}}" required>
                                        </div>
                                        <div class="col-md-1">
                                            <span>العدد</span>
                                        </div>
                                        <div class="col-md-2">
                                            <input type="number" min="1" class="form-control" name="counter4_value" value="{{$counter4_value??''}}" required>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="invoice-wrap">
                                <div class="form-group">
                                    <h4 style="color: #0B792F; margin-bottom: 40px;">وسائل التبرع</h4>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>رقم أورانج</span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="orange_number" value="{{$orange_number??''}}" required >
                                        </div>
                                        <div class="col-md-2">
                                            <span>رقم فودافون</span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="vodafoon_number"value="{{$vodafoon_number??''}}" required >
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span> حساب البنك</span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="bank_account"value="{{$bank_account??''}}"  required>
                                        </div>
                                        <div class="col-md-2">
                                            <span>كود الحساب </span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="account_code"value="{{$account_code??''}}"  required>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="invoice-wrap">
                                <div class="form-group">
                                    <h4 style="color: #0B792F; margin-bottom: 40px;">إعدادت أخرى</h4>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>لينك الفيسبوك</span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="fb_link" value="{{$fb_link??''}}" required>
                                        </div>
                                        <div class="col-md-2">
                                            <span>لينك  الانستجرام </span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="insta_link" value="{{$insta_link??''}}" required>
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">
                                    <div class="col-md-2">
                                            <span>لينك  اليوتيوب </span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="youtube_link"value="{{$youtube_link??''}}" required >
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">
                                        <div class="col-md-2">
                                            <span>الهاتف الأول</span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="phone1"value="{{$phone1??''}}" required >
                                        </div>
                                        <div class="col-md-2">
                                            <span>الهاتف الثاني </span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" name="phone2"value="{{$phone2??''}}"  required>
                                        </div>
                                    </div>
                                    <div class="row" style="margin-bottom: 20px;">

                                    <div class="col-md-2">
                                            <span>إيميل الجمعية</span>
                                        </div>
                                        <div class="col-md-4">
                                            <input type="email" class="form-control" name="email" value="{{$email}}" required>
                                    </div>
                                </div>
                            </div>
                            <div class="invoice-wrap">
                                <div class="form-group">
                                    <div class="vw-ml-action-ls text-right mg-t-20" style="text-align: center" >
                                        <div class="btn-group ib-btn-gp active-hook nk-email-inbox text-center" >
                                            <button class="btn btn-default btn-sm waves-effect"><i class="notika-icon notika-checked"></i> تحديث</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>

            </div>

        </div>
    </div>
    <!-- Invoice area End-->
@stop

resources/views/backend/pages/settings/show.blade.php
@extends('backend.app')
@section('title') New News @stop
@section('content')
    <!-- Breadcomb area Start-->
    <div class="breadcomb-area" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcomb-list">
                        <div class="row" dir="rtl">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="notika-icon notika-support"></i>
                                    </div>
                                    <div class="breadcomb-ctn" style="margin-right: 20px;">
                                        <h2>أنشطة الجمعية</h2>
                                        <p> {{$activity->title}} </p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcomb area End-->
    <!-- Invoice area Start-->
    <div class="alert-area">
        <div class="container">

            <div class="row rounded " style="padding: 20px; margin: 20px 0 ; background-color: white; text-align: right;">
                <div class="col-md-12" >
                    <h4 style="margin: 25px 0; text-align: right;" >{{$activity->title}}</h4>
                    <h6 style="margin: 25px 0; text-align: right;" > {{$activity->programmable->title??''}}</h6>
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="direction: rtl; margin-top: 50px;">

                    <h6> المحتوى:</h6>
                    <div class=" mt-5" style="margin-bottom: 30px;">
                    {!! $activity->content !!}
                    </div>
                    <div class="col-md-12">
                        <h6> الصور:</h6>
                    </div>
                    @if(isset($activity->images))
                        @foreach ($activity->images as $key=>$image)
                            <div class="col-md-4">
                                <img src="{{asset($image)}}" class="img-responsive img-thumbnail" alt="صورة النشاط">
                            </div>
                        @endforeach
                    @else
                        <div class="col-md-4">
                            <img src="{{asset('backend/images/noImage.png')}}"  class="media-object" alt="" >
                            <strong style="color: #dddddd">لم يتم حفظ أي صور</strong>
                        </div>
                    @endif
                    <div class="col-md-12" style="margin-top: 50px;">
                        <h6> الفديوهات:</h6>
                    </div>
                    @if(isset($activity->videos) && $activity->videos[0])
                        @foreach ($activity->videos as $key=>$video)
                            <div class="col-md-4">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" style="height:100% " src=" https://www.youtube.com/embed/{{$video}}" allowfullscreen></iframe>
                                </div>
                            </div>
                        @endforeach
                    @else
                        <div class="col-md-4">
                            <div class="alert alert-danger text-center">
                                لا يوجد
                            </div>
                        </div>
                    @endif
                    <div class="col-md-12">
                        <table class="table table-responsive table-bordered "style="margin-top: 50px;">
                            <tr>
                                <th>تاريخ الإنشاء</th>
                                <td>{{$activity->created_at->toDayDateTimeString()}}</td>
                            </tr>
                            <tr>
                                <th>عدد المشاهدات</th>
                                <td>{{$activity->visit}}</td>
                            </tr>
                        </table>
                        <div class="material-design-btn">
                            <a href="{{route('activities.edit',$activity)}}" class="btn notika-btn-bluegray btn-reco-mg btn-button-mg">تعديل</a>
                            <button data-toggle="modal" data-target="#myModalfive" class="btn notika-btn-red btn-reco-mg btn-button-mg">حذف</button>
                            <div class="modal animated flash" id="myModalfive" role="dialog">
                                <div class="modal-dialog modals-default nk-red">
                                    <form action="{{route('activities.destroy',$activity)}}" method="post" >
                                        @method('DELETE')
                                        @csrf

                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                <h2>حذف العنصر</h2>
                                                <p>من فضلك قم بتأكيد عملية الحذف..</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-default" style="display: inline-block">حذف</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>
    <!-- Invoice area End-->
@stop
@push('js')
    <script !src="">
        $(document).ready(function() {
            $('#summernote').summernote({
                tabsize: 2,
                height: 350,
            });
        });
        $('body').on('click','.frame',function() {
            video = '<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" style="height:100% " src="' + $(this).attr('data-video') + '" allowfullscreen></div>';
            $(this).replaceWith(video);
        });
    </script>
@endpush