routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::view('/', 'frontend.pages.index')->name('/');
Route::view('about-us', 'frontend.pages.about')->name('about');
Route::view('contact-us', 'frontend.pages.contact')->name('contact');
Route::get('F&Q', 'getPagesCtrl@faq')->name('faq');
Route::get('site_activities', 'getPagesCtrl@site_activities')->name('site_activities');
Route::get('site_activities/{id:slug}', 'getPagesCtrl@site_activities_details')->name('site_activities_details');
Route::post('programs/{id:slug}/set_story', 'SuccessStoryController@store')->name('stories.store');
Route::post('programs/{id:slug}/set_help', 'NeedHelpController@store')->name('helps.store');
Route::view('eventDetails', 'frontend.pages.eventDetails')->name('eventDetails');
Route::view('videos', 'frontend.pages.videos')->name('videos');
Route::get('program/{id:slug}', 'getPagesCtrl@program')->name('program');
Route::view('new-news', 'backend.pages.news.new')->name('newNews');



Route::get('/home', 'HomeController@index')->name('home');
Route::get('our_news/{id:slug}','newsCtrl@show')->name('News_Show');
Route::get('site_news/{id:slug}','newsCtrl@showForUser')->name('Site_News_Show');
Route::get('site_news','newsCtrl@SiteIndex')->name('Site_News_Page');

Route::resource('news', 'newsCtrl')->except([
    'show',
]);
Route::resource('activities', 'ActivityController');
Route::resource('faqs', 'FaqController');
Route::resource('programs', 'ProgramController');
Route::resource('stories', 'SuccessStoryController')->except(['store','show','edit','index']);
Route::resource('helps', 'NeedHelpController')->except(['store','show','edit','index']);
Route::resource('slides', 'SliderController')->except(['show','edit']);
Route::resource('talks', 'TalkController')->except(['show','edit']);
Route::resource('mails', 'ContactUsController')->except(['show','edit']);
Route::resource('edumesgs', 'EduMesgController');
Route::resource('settings', 'SettingController');



Route::group(['middleware' => ['auth']], function()
{

    Route::get('settings', 'SettingController@index')->name('settings');
    Route::view('admin', 'backend.pages.index')->name('admin');

});

    Auth::routes(['register' => false,'reset'=>false]);

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    protected $fillable = [
        'text',
        'link',
        'file',

    ];


    use SoftDeletes;

}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostSlideRequest;
use App\Http\Requests\UpdateSlideRequest;
use App\Slider;
use App\Traits\uploadImage;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Slider::all();
        return view('backend.pages.slider.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.slider.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostSlideRequest $request)
    {
        $data = $request->validated();
        if(Slider::count() >= 5){
            return back()->with('error','عفوا لا يمكنك حفظ أكثر من 5 Slides وذلك تجنباً لبطء فتح الموقع');
        }
        $image = $this->uploadImage($request,'file','slides');
        $item = New Slider();
        $item->text = $data['text'];
        $item->file = $image;
        $item->link = $data['link'];
        $item->save();
        session()->flash('success','تم حفظ العنصر بنجاح');
        return redirect()->route('slides.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function show(Slider $slider)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function edit(Slider $slider)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSlideRequest $request, Slider  $slide)
    {

        $data = $request->validated();
        $item = $slide;

        if($request->hasFile('file')){
            \File::Delete($slide->file);
            $image= $this->uploadImage($request,'file','slides');
            $item->file = $image;
        }
        $item->text = $data['text'];
        $item->link = $data['link'];
        $item->save();
        session()->flash('success','تم تحديث بيانات العنصر بنجاح');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slider  $slider
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        $slider = Slider::findOrFail($id);
        \File::Delete($slider->file);
        $slider->delete();
        session()->flash('success','تم حذف العنصر بنجاح');
        return back();
    }
}

resources/views/backend/pages/slider/edit.blade.php
@extends('backend.app')
@section('title') F&Q @stop
@section('content')
    <!-- Breadcomb area Start-->
    <div class="breadcomb-area" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcomb-list">
                        <div class="row" dir="rtl">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="notika-icon notika-support"></i>
                                    </div>
                                    <div class="breadcomb-ctn" style="margin-right: 20px;">
                                        <h2>أخبار الجمعية</h2>
                                        <p> تعديل سؤال  </p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcomb area End-->
    <!-- Invoice area Start-->
    <div class="invoice-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="invoice-wrap">
                        <div class="invoice-img">
                            <img src="{{asset('assets/images/logo.png')}}" alt="" />
                        </div>
                        <div class="invoice-hds-pro">
                            <form action="{{route('faqs.update',$item)}}" method="post" enctype="multipart/form-data">
                                @method('PUT')
                                @csrf()
                                <div class="row" dir="rtl">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"  >
                                        <div class="view-mail-list sm-res-mg-t-30">
                                            <div class="view-mail-hd">
                                                <div class="view-mail-hrd">
                                                    <h2>نشاط جديد</h2>
                                                </div>
                                            </div>
                                            <div class="cmp-int mg-t-20">
                                                <div class="row">
                                                    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-12">
                                                        <div class="cmp-int-lb cmp-int-lb1 text-right">
                                                            <span>السؤال: </span>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-11 col-md-10 col-sm-10 col-xs-12">
                                                        <div class="form-group">
                                                            <div class="nk-int-st cmp-int-in cmp-email-over">
                                                                <input type="text" name="title" value="{{$item->title}}" class="form-control" placeholder="" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-1 col-md-2 col-sm-2 col-xs-12">
                                                        <div class="cmp-int-lb cmp-int-lb1 text-right">
                                                            <span>الجواب: </span>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-11 col-md-10 col-sm-10 col-xs-12">
                                                        <div class="form-group">
                                                            <div class="cmp-int-box mg-t-20">
                                                                <textarea id="summernote" class="form-control" style="height: 200px;"  name="content">{!! $item->content !!}</textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                            <div class="vw-ml-action-ls text-right mg-t-20" style="text-align: center" >
                                                <div class="btn-group ib-btn-gp active-hook nk-email-inbox text-center" >
                                                    <button class="btn btn-default btn-sm waves-effect"><i class="notika-icon notika-checked"></i> حفظ البيانات الجديدة</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Invoice area End-->
@stop
@push('js')
    <script !src="">
        $(document).ready(function() {
            $('#summernote').summernote({
                tabsize: 2,
                height: 350,
            });
        });
        $(document).ready(function() {
            var max_fields      = 10; //maximum input boxes allowed
            var wrapper   		= $(".input_fields_wrap"); //Fields wrapper
            var add_button      = $(".add_field_button"); //Add button ID

            var x = 1; //initlal text box count
            $(add_button).click(function(e){ //on add input button click
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class=""><input type="url" class="form-control" style="margin-top: 20px;"  name="youtubeLink[]"  placeholder="ادخل لينك يوتيوب.." required /><a href="#" class="remove_field btn btn-xs btn-danger" style="margin-top: 10px">حذف</a></div>'); //add input box
                }
            });

            $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
        $(document).ready(function() {
            var max_fields      = 10; //maximum input boxes allowed
            var wrapper   		= $(".input_images_wrap"); //Fields wrapper
            var add_button      = $(".add_image_button"); //Add button ID


            var x = 1; //initlal text box count
            $(add_button).click(function(e){ //on add input button click
                var number          = $(".input_images_wrap input").length;
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class="col-md-4"> <img class="rounded" width="400" height="260" style="height: 260px" id="imgPreview'+number+'" src="" alt=""> <input type="file" class="form-control-file"  name="file[]"  onchange="readURL(this,\'#imgPreview'+number+'\')"  required /> <a href="#" class="remove_image btn btn-xs btn-danger" style="margin-top: 10px">حذف</a></div>'); //add input box
                }
            });

            $(wrapper).on("click",".remove_image", function(e){ //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
    </script>
@endpush

resources/views/backend/pages/slider/index.blade.php
@extends('backend.app')
@section('title') Slides @stop
@section('content')
    <!-- Breadcomb area Start-->
    <div class="breadcomb-area" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcomb-list">
                        <div class="row" dir="rtl">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="notika-icon notika-support"></i>
                                    </div>
                                    <div class="breadcomb-ctn" style="margin-right: 20px;">
                                        <h2>سلايدرز</h2>
                                        <p> جميع السلايدرز</p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcomb area End-->
    <!-- Invoice area Start-->
    <div class="alert-area">
        <div class="container">
            @if(count($data) == 0 )
                <div class="row" >
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" >
                        <p class="alert alert-danger text-center text-danger "> لم يتم حفظ أي بيانات بعد!!</p>
                    </div>
                </div>
            @else

            <div class="row rounded " style="padding: 20px; margin: 20px 0 ; background-color: white; text-align: right;">

                <div class="col-lg-12 col-md-8 col-sm-12 col-xs-12 table-responsive" style="direction: rtl">
                    <table class="table table-bordered ">
                        <tr>
                            <th>#</th>
                            <th>الصورة</th>
                            <th>النص</th>
                            <th>تاريخ آخر تعديل</th>
                            <th>العمليات</th>
                        </tr>
                        @foreach($data as  $key=>$row)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td style="width: 30%">
                                    <img src="{{asset($row->file)}}" style="width: 100%" class="img-responsive " alt="">
                                </td>
                                <td>
                                    <p>{{$row->text??'لا يوجد'}}</p>
                                </td>
                                <td>{{$row->updated_at->toDayDateTimeString()}}</td>
                                <td class="material-design-btn text-center" style="width: 20%">
                                    @if(!is_null($row->link))
                                        <a href="{{$row->link}}" style="margin-top: 10px ;" class="btn notika-btn-green btn-reco-mg btn-button-mg">اتباع الرابط</a>
                                    @endif
                                        <button data-toggle="modal" data-target="#myModalSE{{$key}}" style="margin-top: 10px ;" class="btn notika-btn-deeppurple btn-reco-mg btn-button-mg">تعديل</button>
                                        <div class="modal animated rubberBand" id="myModalSE{{$key}}" role="dialog">
                                            <div class="modal-dialog modal-large ">
                                                <form action="{{route('slides.update',$row)}}" method="post"  enctype="multipart/form-data">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" style="background-color: #5a4a9a" data-dismiss="modal">&times;</button>
                                                        </div>
                                                        <div class="modal-body card ">
                                                            <h2>تعديل slide رقم {{$key+1}}</h2>
                                                            <div class="row">
                                                                <div class="col-lg-1 col-md-2 col-sm-2 col-xs-12">
                                                                    <div class="cmp-int-lb cmp-int-lb1 text-right">
                                                                        <span>الصورة: </span>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-11 col-md-10 col-sm-10 col-xs-12">
                                                                    <div class="form-group">
                                                                        <div class="nk-int-st cmp-int-in cmp-email-over">
                                                                            <input type="file" name="file" class="form-control"  onchange="readURL(this,'#imgPreview1{{$key}}')"  />
                                                                        </div>
                                                                        <img src="{{$row->file}}" alt="" width="450" class="img-responsive" id="imgPreview1{{$key}}" >
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-1 col-md-2 col-sm-2 col-xs-12">
                                                                    <div class="cmp-int-lb cmp-int-lb1 text-right">
                                                                        <span>النص: </span>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-11 col-md-10 col-sm-10 col-xs-12">
                                                                    <div class="form-group">
                                                                        <div class="cmp-int-box mg-t-20">
                                                                            <textarea class="form-control" maxlength="100"  name="text">{{$row->text}}</textarea>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-1 col-md-2 col-sm-2 col-xs-12">
                                                                    <div class="cmp-int-lb cmp-int-lb1 text-right">
                                                                        <span>اللينك: </span>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-11 col-md-10 col-sm-10 col-xs-12">
                                                                    <div class="form-group">
                                                                        <div class="cmp-int-box mg-t-20">
                                                                            <input type="text" name="link" class="form-control" placeholder="" value="{{$row->link}}"/>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>


                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="submit" class="btn notika-btn-deeppurple btn-reco-mg btn-button-mg" style="display: inline-block">تحديث</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>

                                        <button data-toggle="modal" data-target="#myModalSD{{$key}}" style="margin-top: 10px ;" class="btn notika-btn-red btn-reco-mg btn-button-mg">حذف</button>
                                        <div class="modal animated flash" id="myModalSD{{$key}}" role="dialog">
                                            <div class="modal-dialog modals-default nk-red">
                                                <form action="{{route('slides.destroy',$row)}}" method="post" >
                                                    @method('DELETE')
                                                    @csrf

                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <h2>حذف العنصر</h2>
                                                            <p>من فضلك قم بتأكيد عملية الحذف..</p>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="submit" class="btn btn-default" style="display: inline-block">حذف</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                </td>
                            </tr>
                        @endforeach

                    </table>

                </div>


            </div>
            @endif

        </div>
    </div>
    <!-- Invoice area End-->
@stop
@push('js')
    <script !src="">
        $(document).ready(function() {
            $('#summernote').summernote({
                tabsize: 2,
                height: 350,
            });
        });
    </script>
@endpush

resources/views/backend/pages/slider/show.blade.php
@extends('backend.app')
@section('title')  F&Q @stop
@section('content')
    <!-- Breadcomb area Start-->
    <div class="breadcomb-area" >
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcomb-list">
                        <div class="row" dir="rtl">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="notika-icon notika-support"></i>
                                    </div>
                                    <div class="breadcomb-ctn" style="margin-right: 20px;">
                                        <h2>الأسئلة الشائعة</h2>
                                        <p> {{$item->title}} </p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcomb area End-->
    <!-- Invoice area Start-->
    <div class="alert-area">
        <div class="container">

            <div class="row rounded " style="padding: 20px; margin: 20px 0 ; background-color: white; text-align: right;">
                <div class="col-md-12" >
                    <h4 style="margin: 25px 0; text-align: right;" >{{$item->title}}</h4>
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="direction: rtl; margin-top: 50px;">

                    <h6> الجواب:</h6>
                    <div class=" mt-5" style="margin-bottom: 30px;">
                    {!! $item->content !!}
                    </div>

                    <div class="col-md-12">
                        <table class="table table-responsive table-bordered "style="margin-top: 50px;">
                            <tr>
                                <th>تاريخ الإنشاء</th>
                                <td>{{$item->created_at->toDayDateTimeString()}}</td>
                            </tr>
                        </table>
                        <div class="material-design-btn">
                            <a href="{{route('faqs.edit',$item)}}" class="btn notika-btn-bluegray btn-reco-mg btn-button-mg">تعديل</a>
                            <button data-toggle="modal" data-target="#myModalfive" class="btn notika-btn-red btn-reco-mg btn-button-mg">حذف</button>
                            <div class="modal animated flash" id="myModalfive" role="dialog">
                                <div class="modal-dialog modals-default nk-red">
                                    <form action="{{route('faqs.destroy',$item)}}" method="post" >
                                        @method('DELETE')
                                        @csrf

                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                <h2>حذف العنصر</h2>
                                                <p>من فضلك قم بتأكيد عملية الحذف..</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-default" style="display: inline-block">حذف</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

            </div>

        </div>
    </div>
    <!-- Invoice area End-->
@stop
@push('js')
    <script !src="">
        $(document).ready(function() {
            $('#summernote').summernote({
                tabsize: 2,
                height: 350,
            });
        });
        $('body').on('click','.frame',function() {
            video = '<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" style="height:100% " src="' + $(this).attr('data-video') + '" allowfullscreen></div>';
            $(this).replaceWith(video);
        });
    </script>
@endpush